modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="create_veridium_expansion"
version="0.9"
displayName="Create: Veridium Expansion"
authors="TeK Sama"
description='''Adds Veridium alloy tools, armors, jetpacks and weapon upgrades for Create and CSA.'''

[[dependencies.create_veridium_expansion]]
modId="create"
mandatory=true
versionRange="[6.0,)"
ordering="AFTER"
side="BOTH"
